services:
  postgres:
    image: postgres:18.3
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      USER_DATABASE_NAME: ${USER_DATABASE_NAME}
      TRIP_DATABASE_NAME: ${TRIP_DATABASE_NAME}
      NOTIFICATION_DATABASE_NAME: ${NOTIFICATION_DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init_postgres.sh:/docker-entrypoint-initdb.d/init_postgres.sh
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

  user-service:
    build: ./user-service
    env_file:
      - .env
    environment:
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      USER_DATABASE_URL: ${USER_DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_LIFETIME: ${JWT_ACCESS_TOKEN_LIFETIME}
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    depends_on:
      postgres:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    env_file:
      - .env
    environment:
      NOTIFICATION_SERVICE_PORT: ${NOTIFICATION_SERVICE_PORT}
      NOTIFICATION_DATABASE_URL: ${NOTIFICATION_DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"
    depends_on:
      postgres:
        condition: service_healthy

  trip-service:
    build: ./trip-service
    env_file:
      - .env
    environment:
      TRIP_SERVICE_PORT: ${TRIP_SERVICE_PORT}
      TRIP_DATABASE_URL: ${TRIP_DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      USER_SERVICE_URL: http://user-service:${USER_SERVICE_PORT}
      NOTIFICATION_SERVICE_URL: http://notification-service:${NOTIFICATION_SERVICE_PORT}
    ports:
      - "${TRIP_SERVICE_PORT}:${TRIP_SERVICE_PORT}"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data: