#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DATABASE_USERNAME WITH PASSWORD '$DATABASE_PASSWORD';
    CREATE DATABASE ${USER_DATABASE_NAME} OWNER $DATABASE_USERNAME;
    CREATE DATABASE ${TRIP_DATABASE_NAME} OWNER $DATABASE_USERNAME;
    CREATE DATABASE ${NOTIFICATION_DATABASE_NAME} OWNER $DATABASE_USERNAME;
EOSQL