spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: user-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${USER_DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: ${USER_SERVICE_PORT}

jwt:
  access-token:
    secret: ${JWT_SECRET}
    expiration: ${JWT_ACCESS_TOKEN_LIFETIME}